# Generated by Django 4.0.6 on 2023-01-18 08:17

import app.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, unique=True)),
                ('last_name', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[app.validators.phone_number_validator], verbose_name='Phone Number')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('id_number', models.CharField(max_length=255, null=True, unique=True, verbose_name='ID Number')),
                ('kin_first_name', models.CharField(max_length=255, unique=True)),
                ('kin_last_name', models.CharField(max_length=255, unique=True)),
                ('kin_phone_number', models.CharField(max_length=20, unique=True, validators=[app.validators.phone_number_validator], verbose_name='Phone Number')),
                ('kin_id_number', models.CharField(max_length=255, null=True, unique=True, verbose_name='ID Number')),
                ('kin_relationship', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('product_category', models.CharField(max_length=255, unique=True)),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_visible', models.BooleanField(default=False, help_text='Is the classification visible on the frontend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('policy_number', models.CharField(max_length=255, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.customer')),
                ('product_issued', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
