# Generated by Django 4.0.6 on 2023-01-19 06:57

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='kin_id_number',
            field=models.IntegerField(null=True, unique=True, verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='kin_phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[app.validators.phone_number_validator], verbose_name='Phone Number'),
        ),
    ]
